.PHONY: gen-swagger run-api migrate-up migrate-down monitoring-up monitoring-down

DB_URL ?= postgres://user:pass@localhost:5432/secure-dag?sslmode=disable

gen-swagger:
	@swag init -g cmd/api/server.go -o docs/swagger

run-api:
	@go run cmd/api/server.go

migrate-up:
	@go run cmd/migrate/main.go -action=up -conn=$(DB_URL)

migrate-down:
	@go run cmd/migrate/main.go -action=down -conn=$(DB_URL)

monitoring-up:
	@docker-compose -f docker-compose.monitoring.yml up -d

monitoring-down:
	@docker-compose -f docker-compose.monitoring.yml down
